name: Skylands
version: ${pluginVersion}
main: me.lokkee.skylands.Skylands
api-version: 1.17
author: LOKKEE
description: Skylands is an upcoming open-source System, with all sorts of RPG related functionalities.
